# Numpy

Numpy is one of the most important foundational packages for Numerical computing in python<br>
Some of the important things in Numpy<br>
1. ndrray - multidimensional array for fast array-oriented and broadcasting operations
2. Fast mathematical opertions without for loops
3. reading/writing array data to the disk
4. memory-mapped files
5. Linear Algebra, random number generation

In [2]:
# Creating numpy array

import numpy as np

arr_1 = np.array([1,2,3,4,5,6])
print(arr_1)

[1 2 3 4 5 6]


In [3]:
# Creating numpy array using list

person_height = [5.2,  5.4, 4.4, 4.5, 5.6, 6.0]
person_height = np.array(person_height)
print(person_height)

[5.2 5.4 4.4 4.5 5.6 6. ]


In [4]:
# Using type() function to know the datatype

type(person_height)

numpy.ndarray

### Advantages of Numpy over list

In [5]:
# Add 1 to every element in a list

num_list = [1,2,3,4,5]
modified_list = [i + 1 for i in num_list]
modified_list

[2, 3, 4, 5, 6]

In [6]:
# Now using numpy

arr_3 = np.array(num_list)
modified_arr = arr_3 + 1
modified_arr

array([2, 3, 4, 5, 6])

In [7]:
# Creating Numpy array using arange function

my_array = np.arange(10)
print(my_array)

# Creating for list in python

my_list = list(range(10))
print(my_list)

[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


#### Built-in Function to Create an Array

##### Array of Zeroes
 The zeros() will create a new array of the specified size with the contents filled with zero values.

In [8]:
arrr = np.zeros([3 , 2])
print(arrr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


##### An array of Ones
The ones() will create a new array of the specified size with its elements as unity.

In [9]:
arrr = np.ones([3 , 2])
print(arrr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


**An Empty array**

The empty() will create an empty matrix.

In [10]:
# create a numpy array with 3 rows and 2 columns
my_array = np.empty([3, 2])

# print the array
print(my_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
my_array = np.empty((2, 2), dtype = float)

print(my_array)

[[3.26133733e-315 0.00000000e+000]
 [4.94065646e-324             nan]]


#### An array of random numbers

The **random()** function returns random numbers in the half-open interval [0.0, 1.0). The half-open interval includes 0 but excludes 1. The required number of random numbers is passed through the ‘size’ parameter.

In [12]:
# create 2D array of 3 rows and 2 columns of random numbers
my_array = np.random.random(size = (3, 2))

my_array

array([[0.064273  , 0.32071755],
       [0.70966978, 0.316009  ],
       [0.65170585, 0.13339424]])

The **randn()** creates an array of the given shape with random variables from a uniform distribution between (0, 1).

In [13]:
my_array = np.random.randn(3, 2)

my_array

array([[ 0.61539055, -0.65342554],
       [ 0.25503906,  1.02504456],
       [ 0.62135185, -0.96452664]])

The **randint()** returns random integers from low (inclusive) to high (exclusive).

In [14]:
# create an array of 3 of random numbers between 2 and 9
# the randint() will not include 10, the numbers will be generated between 2 and 9 (both inclusive)
my_array = np.random.randint(2, 10, (3, 6))

my_array

array([[6, 7, 4, 4, 9, 5],
       [6, 6, 3, 7, 8, 5],
       [4, 5, 3, 5, 4, 8]])

#### Create an array using arange()
arange() function creates an array of numbers between the given range.

start: start value of interval (inclusive), 0 is the default value.

stop: stop value of interval (exclusive).

step: returns numbers with given step_size.

In [15]:
sequence = np.arange(start = 10, stop = 40, step = 2)

sequence

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

## Attributes of Array
It is defined as a specification that defines a property of an object. Attributes of the numpy array do not have parentheses following them|

**ndim:**<br>
Prints the dimension (number of axes) of the numpy array

In [16]:
quantity = np.array([(11, 32, 23), (34, 55, 46)])
print(quantity.ndim)

2


**itemsize:**<br>
Prints the memory occupied by each element.

In [17]:
quantity = np.array([(4, 5, 6, 2, 75, 3)])
print(quantity.itemsize)

8


**dtype:**<br>
Prints the data type along with the size in bytes.

In [18]:
quantity = np.array([(1, 2, 3)])
print(quantity.dtype)

int64


**size:**<br>
Prints the number of elements in the array.

**shape**<br>
Prints the number of rows and columns of the array.

In [19]:
quantity = np.array([(1, 2, 3, 4, 5, 6), (1,2,3,4,5,6,)])
print(quantity.size)
print(len(quantity))
print(quantity.shape)

12
2
(2, 6)


## Functions/method:
A method is a function that belongs to an object. It takes parameters in the parentheses and returns the modified array.

**reshape:**<br>
The reshape() is used to change the number of rows and columns of an array without changing the data.<br>

In [20]:
# create an array
quantity_1 = np.array([(8, 9, 10), (11, 12, 13)])

# print the array
print("The original array:\n", quantity_1)

The original array:
 [[ 8  9 10]
 [11 12 13]]


In [21]:
# change the shape
quantity_2 = quantity_1.reshape(3, 2)

# print the array
print("The reshaped array:\n", quantity_2)

The reshaped array:
 [[ 8  9]
 [10 11]
 [12 13]]


## Indexing Array

**Indexing in 1 dimension**

In [22]:
# declare an array
quantity = np.array([11, 22, 33, 24, 57, 473])

# print the array
print(quantity)

[ 11  22  33  24  57 473]


In [24]:
# Each element in the array can be accessed by passing the positional index of the element.

# get the 1st element
print(quantity[0])

11


**Indexing in 2 dimensions**

In [25]:
# declare a 2D array
quantity = np.array([[101, 231, 321],
                     [412, 512, 622],
                     [712, 821, 912]])

# print the array
quantity

array([[101, 231, 321],
       [412, 512, 622],
       [712, 821, 912]])

In [26]:
# get the element in 3rd row and 2nd column
print(quantity[2, 1])

821


In [27]:
# we can pass ith row and jth column in separate brackets ([])
print(quantity[2][1])

821


## Slicing Array

**Slicing a 1D array**

In [28]:
# declare an array
price = np.array([101, 121, 112, 123, 114])

# pick the second, third, and fourth element from the array
new_price = price[1:4]

# print the array
new_price

array([121, 112, 123])

In [29]:
# first three elements
price[:3]

array([101, 121, 112])

In [30]:
# all the elements from 112
price[2:]

array([112, 123, 114])

In [31]:
# get the complete array
price[:]

array([101, 121, 112, 123, 114])

**Slicing a 2D array**

In [32]:
# declare a 2D array
prices = np.array([[101, 131, 122, 113, 143],
                   [145, 165, 137, 318, 193],
                   [240, 241, 252, 253, 324],
                   [225, 126, 727, 928, 129]])

# print the array
prices

array([[101, 131, 122, 113, 143],
       [145, 165, 137, 318, 193],
       [240, 241, 252, 253, 324],
       [225, 126, 727, 928, 129]])

**Note:** The index returns an element of the array, the slice returns a list of elements.

## Operations on a 1D Array

In [33]:
# declare two arrays
# first array
prices = np.array([120, 230, 310, 410, 150])

# print the array
print("The first array is", prices, "has length", len(prices))

The first array is [120 230 310 410 150] has length 5


In [34]:
# second array
quantity = np.arange(5)

# print the array
print("The second array is", quantity, "has length", len(quantity))

The second array is [0 1 2 3 4] has length 5


In [35]:
#Add the two arrays

num_array = prices + quantity
num_array

array([120, 231, 312, 413, 154])

In [36]:
# declare another array
num_array = np.array([1, 2, 3, 5])

# print the array
print("The new array is", num_array, "has length", len(num_array))

The new array is [1 2 3 5] has length 4


In [37]:
num_array + quantity

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

**Remark:** If you try to add arrays with different dimensions, you get an error.  

In [38]:
# multiply each element in the array by 4
quantity * 4

array([ 0,  4,  8, 12, 16])

In [39]:
# get square of each element
quantity ** 2

array([ 0,  1,  4,  9, 16])

## Operations on a 2D Array

Let’s create 2 two-dimensional arrays, array_a and array_b.

In [40]:
# declare two arrays
# first array
quanitity_A = np.array([[33, 12], [70, 61]])

# print the array
print("The first array is \n", quanitity_A)

The first array is 
 [[33 12]
 [70 61]]


In [41]:
# second array
quanitity_B  = np.array([[43, 51], [72, 81]])

# print the array
print("The second array is \n", quanitity_B)

The second array is 
 [[43 51]
 [72 81]]


In [42]:
# add the 2 arrays
quanitity_A + quanitity_B

array([[ 76,  63],
       [142, 142]])

In [44]:
# multiply the 2 arrays
quanitity_A * quanitity_B

array([[1419,  612],
       [5040, 4941]])

'+=' operation on the `quanitity_A` is equivalent to adding a specified value to each element of the array. The original array gets modified using this operation.


In [45]:
# add 2 to each element
quanitity_A += 2
quanitity_A

array([[35, 14],
       [72, 63]])

**Matrix Multiplication**<br>

Use '@' operator to perform matrix multiplication (or matrix product).

In [46]:
quanitity_A @ quanitity_B

array([[2513, 2919],
       [7632, 8775]])

The same output can also be obtained by the dot().

In [47]:
quanitity_A.dot(quanitity_B)

array([[2513, 2919],
       [7632, 8775]])

## Arithmetic Functions in Numpy

In [48]:
# given array
performance_scores = np.array([5, 7, 8, 2, 4])

# print the array
performance_scores

array([5, 7, 8, 2, 4])

**sum():**<br>
The sum() function adds all the values in the array and gives a scalar output.

**min():**<br>
The min function finds the lowest value in the array.

**power():**<br>
The power function raises the numbers in the array to the given value.

In [49]:
# add all the elements of 'performance_scores'
performance_scores.sum()

np.int64(26)

In [50]:
# find minimum of 'performance_scores'
performance_scores.min()

np.int64(2)

In [51]:
# get cube of elements of 'performance_scores'
np.power(performance_scores, 3)

array([125, 343, 512,   8,  64])

**Using the axis parameter**<br>
Use the axis parameter with value 0, to find the sum of all the values in a single column.

In [52]:
# create a 2D array of random integers
num_array = np.random.randint(1, 10, (2, 3))
num_array

array([[4, 7, 2],
       [7, 1, 4]])

In [53]:
# obtain the sum over columns
num_array.sum(axis = 0)

array([11,  8,  6])

In [54]:
# obtain the sum over rows
num_array.sum(axis = 1)

array([13, 12])

In [55]:
# obtain the min over rows
num_array.min(axis = 1)

array([2, 1])

In [56]:
# obtain the max over columns
num_array.max(axis = 0)

array([7, 7, 4])

## Concatenation of Array

The arrays can be concatenated only if they have the same shape, except in the dimension corresponding to the axis of concatenation.

**Concatenate 1D array**

In [57]:
# concatenate two 1D arrays
# production on day 1
production_day_1 = np.array([11, 22, 13])

# production on day 2
production_day_2 = np.array([23, 22, 12])

# concatenate the two array giving the production for 2 days
np.concatenate([production_day_1, production_day_2])

array([11, 22, 13, 23, 22, 12])

In [58]:
# production on day 3
production_day_3 = np.array([23, 45])

# concatenate the two array giving the production for 3 days
total_produce = np.concatenate([production_day_1, production_day_2, production_day_3])

# print total_produce
total_produce

array([11, 22, 13, 23, 22, 12, 23, 45])

**Concatenate 2D array**

In [60]:
# create a 2D array
scores_player_1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
scores_player_1

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
# create a 2D array
scores_player_2 = np.array([[5, 6, 3],
                 [4, 9, 6]])
scores_player_2

array([[5, 6, 3],
       [4, 9, 6]])

## Splitting of Array

Splitting is used to split the array into multiple sub-arrays. It is the opposite of concatenation, which is implemented by functions like split(), hsplit(), and so on.


**split():**

In [62]:
# declare an array
array_x = np.arange(8)

# split the array into sub-arrays
np.split(array_x, 2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [63]:
# declare an array
array_x = np.arange(7)

# split the array into sub-arrays
np.split(array_x, 2)

ValueError: array split does not result in an equal division

**Remark:** The split() function does not allow the integer (N) as the number of splits if N does not divide the array into sub-arrays of equal length
                    

**array_split():** It is used to split the array into sub-arrays. It takes the integer 'N' as the input for the number of splits, even if 'N' does not divide the array into sub-arrays of equal length.<br>

In [64]:
# split 'array_x' into 3 sub-arrays using 'array_split'
np.array_split(array_x, 3)

[array([0, 1, 2]), array([3, 4]), array([5, 6])]